// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getMoveProb
NumericMatrix getMoveProb(NumericVector river, NumericMatrix moveProb);
RcppExport SEXP wbPersist_getMoveProb(SEXP riverSEXP, SEXP moveProbSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type river(riverSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type moveProb(moveProbSEXP);
    __result = Rcpp::wrap(getMoveProb(river, moveProb));
    return __result;
END_RCPP
}
// grow
NumericVector grow(NumericMatrix pars, IntegerVector river, NumericVector startLength, NumericVector flow, NumericVector biomass, NumericVector performance);
RcppExport SEXP wbPersist_grow(SEXP parsSEXP, SEXP riverSEXP, SEXP startLengthSEXP, SEXP flowSEXP, SEXP biomassSEXP, SEXP performanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type river(riverSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type startLength(startLengthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type flow(flowSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type biomass(biomassSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type performance(performanceSEXP);
    __result = Rcpp::wrap(grow(pars, river, startLength, flow, biomass, performance));
    return __result;
END_RCPP
}
// survive
NumericVector survive(NumericVector river, NumericVector stage, NumericVector forkLength, NumericMatrix phiBeta5, NumericMatrix envLogitPhi);
RcppExport SEXP wbPersist_survive(SEXP riverSEXP, SEXP stageSEXP, SEXP forkLengthSEXP, SEXP phiBeta5SEXP, SEXP envLogitPhiSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type river(riverSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type stage(stageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type forkLength(forkLengthSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phiBeta5(phiBeta5SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type envLogitPhi(envLogitPhiSEXP);
    __result = Rcpp::wrap(survive(river, stage, forkLength, phiBeta5, envLogitPhi));
    return __result;
END_RCPP
}
