# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Return the probability of moving to each river given a starting location
#'
#' Requires that movement probabilities are given as a nRivers x nRivers matrix, so this needs to be run for a single season.
#'
#' @param river Vector of starting locations
#' @param moveProb Matrix of season-specific movement probabilities
#' @export
getMoveProb <- function(river, moveProb) {
    .Call('wbPersist_getMoveProb', PACKAGE = 'wbPersist', river, moveProb)
}

#'Estimates actual growth given performance, other covariates, and parameters
#'
#'@param pars Matrix of betas from growth model
#'@param river Vector of river locations for individuals
#'@param startLength Vector of starting lengths
#'@param flow Vector of mean flow for the growth period
#'@param biomass Vector of brook trout biomass during the growth period
#'@param performance Vector of growth performance from the \code{getGrowthPerformance()}
#'@export
grow <- function(pars, river, startLength, flow, biomass, performance) {
    .Call('wbPersist_grow', PACKAGE = 'wbPersist', pars, river, startLength, flow, biomass, performance)
}

#' Gets a survival probability given the environmental contribution, start length, and parameters
#'
#' @param river Vector of river locations of individuals
#' @param stage Vector of stages
#' @param forkLength Vector of lengths of individuals
#' @param phiBeta5 Matrix of length betas
#' @param envLogitPhi Matrix of environmental contribution to surival from \code{getEnvLogitPhi()}
#' @export
#' @useDynLib wbPersist
#' @importFrom Rcpp sourceCpp
survive <- function(river, stage, forkLength, phiBeta5, envLogitPhi) {
    .Call('wbPersist_survive', PACKAGE = 'wbPersist', river, stage, forkLength, phiBeta5, envLogitPhi)
}

