# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getMoveProb <- function(river, moveProb) {
    .Call('wbPersist_getMoveProb', PACKAGE = 'wbPersist', river, moveProb)
}

grow <- function(pars, river, startLength, flow, biomass, performance) {
    .Call('wbPersist_grow', PACKAGE = 'wbPersist', pars, river, startLength, flow, biomass, performance)
}

survive <- function(river, stage, forkLength, phiBeta5, envLogitPhi) {
    .Call('wbPersist_survive', PACKAGE = 'wbPersist', river, stage, forkLength, phiBeta5, envLogitPhi)
}

